### ISSUE TITLE
config.json is not created

### ISSUE THREAD

**Issue by netson** [elastic/puppet-logstashforwarder#10]
Hey, some more feedback for your module! :+1: 

On a clean system, it seems like the config.json file is not created; it seems the logstashforwarder_config type is responsible for this. I don't know ruby, but maybe it is a matter of adding the following line to the top of ```lib/puppet/type/logstashforwarder_config.rb```

```ruby
require 'puppet/type/file/ensure'
```
For now I was able to work around it by adding this to the config.pp of the module:

```puppet
    file { "${logstashforwarder::configdir}/config.json":
        ensure  => present,
        require => File[ $logstashforwarder::configdir ],
        before  => Logstashforwarder_config [ 'lsf-config' ]
    }
```

**Comment by electrical** [comment]
Hi,

I finally managed to do some work on the module and add acceptance tests to it.
All tests are passing so far.
Please try out the released version and open a new issue if you still have issues.
