### ISSUE TITLE
init script

### ISSUE THREAD

**Issue by eskp** [elastic/puppet-logstashforwarder#11]
Hey Richard, thanks for the module!

At the moment supplied init script is pointing to the wrong config file location and fails silently.

DAEMON_ARGS="-config /etc/logstash-forwarder -spool-size 100 -log-to-syslog"

1) Logstashforwarder gets installed in /etc/logstashforwarder (on Ubuntu anyway)

2) Looks like Logstashforwarder requires the config file and not the directory

Cheers,

Simon

**Comment by electrical** [comment]
Hi,

LSF 0.4.0 has been released a while ago and the puppet module has been updated.
Can you validate it works for you now? Please open a new issue if you are having problems.
