### ISSUE TITLE
Does not work now that the debian packages have been purged.

### ISSUE THREAD

**Issue by topperge** [elastic/puppet-logstashforwarder#20]
The debian package repo was purged 2 days ago as referenced here
https://github.com/elasticsearch/logstash-forwarder/issues/184

The script is now broken and code to build from source must be added if you don't build packages yourself
https://github.com/elasticsearch/puppet-logstashforwarder/blob/master/manifests/repo.pp#L35

**Comment by jordansissel** [comment]
Sorry, if anything was using the logstash forwarder apt repo, it was a bug and not supported. I went through the motions of deelting this repo months ago, but I think I missed one location and it wasn't actually purged until I resolved that problem this weekend.

**Comment by jordansissel** [comment]
This puppet module is not actively maintained at this time, also. The last update was a year ago.

**Comment by jordansissel** [comment]
@electrical should we pull this offline to avoid confusing users further? I pulled the logstash forwarder binary offline because it has bugs and I'm tired of punishing users with the same bugs for the past year. Maybe we should do the same with this repo until we are able to make time to invest in it?

**Comment by poolski** [comment]
That would make sense. Maybe replace it with more up-to-date (if
applicable) build guides for FPM so that people can build and maintain
their own packages of LSF.

**Comment by electrical** [comment]
A release has been done of the puppet module to support LSF 0.4.0
Closing this issue.
