### ISSUE TITLE
Port setting

### ISSUE THREAD

**Issue by snobear** [elastic/puppet-logstashforwarder#22]
Hi, thanks for this puppet module.  Two documentation-related questions:

1. What is the default port setting for the logstash forwarder?

2. How do you explicitly set the port?  I'm assuming something like:

```
 class { 'logstashforwarder':
   servers  => [ 'logstash.yourdomain.com:5000' ],
...
```

**Comment by poolski** [comment]
1. The default port is TCP 5043

2. Yes, that sounds about right.

**Comment by snobear** [comment]
Perfect, thanks!
