### ISSUE TITLE
Support for logstash-forwarder 0.4.0

### ISSUE THREAD

**Issue by insertjokehere** [elastic/puppet-logstashforwarder#23]
Presently these manifests do not work with logstash-forwarder 0.4.0 (on Debian at least, haven't tried the RPM, but I suspect the same issues would be present), because the /etc/defaults file it writes is missing several settings required for the new init script

**Comment by electrical** [comment]
Hi,

The older version of LSF didn't had full init script support so had to supply them with the module.
With 0.4.0 there are better init scripts and i should re-use those indeed.
I'll try to make some time to make the module work with LSF 0.4.0 as soon as i can.

**Comment by electrical** [comment]
Hi,

The module finally has an official release that supports LSF 0.4.0
If you have any issues with it please open a new issue.
