### ISSUE TITLE
Could not autoload puppet/type/logstashforwarder_config

### ISSUE THREAD

**Issue by kariboe** [elastic/puppet-logstashforwarder#33]
I'm busy testing the logstashforwarder puppet module in my Puppet Enterprise (3.7.1) setup but I'm encountering this error: 

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/type/logstashforwarder_config: uninitialized constant Puppet::Type::File::Owner on node xxx.yyy.zz

Any help is appreciated to resolve this bug.

**Comment by electrical** [comment]
That's weird as the acceptance tests i do with PE 3.7.1 passed without any issues so far.
( See http://build-eu-00.elastic.co/view/Puppet/job/Puppet_LogstashForwarder_Acceptance_Tests_Commit/ for details )
I'll try to do some more digging on this issue.

**Comment by kariboe** [comment]
Can I assist in further debugging?

**Comment by electrical** [comment]
Could you try out something for me.
https://github.com/elastic/puppet-logstashforwarder/blob/master/lib/puppet/type/logstashforwarder_config.rb#L1
Could you remove that top line in your local copy and run again?

Thanks!

**Comment by kariboe** [comment]
Fixes the issue! Thanks

**Comment by electrical** [comment]
Released 0.1.1 to fix this issue. Thanks for reporting it and trying out the fix!
