### ISSUE TITLE
Please add hieradata support

### ISSUE THREAD

**Issue by abo-adapt** [elastic/puppet-logstashforwarder#38]
It would be nice to have this module draw values from hiera by default.

**Comment by poolski** [comment]
It does this already. You need to refer to the class parameters by name in your hiera data. Usually it's at the top level of your hash, e.g:

```
{
  "logstashforwarder:: server": [" hostname.example.net"]
}
```

**Comment by abo-adapt** [comment]
Right. It works. My bad :)
