### ISSUE TITLE
Problem with the RPM

### ISSUE THREAD

**Issue by blee1170** [elastic/puppet-logstashforwarder#40]
When puppet tries to install the RPM I get the following error:
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install logstash-forwarder' returned 1: Error in PREIN scriptlet in rpm package logstash-forwarder-0.4.0-1.x86_64
/var/tmp/rpm-tmp.LDCPp9: line 10: 14553 Segmentation fault      (core dumped) useradd -r -g logstash-forwarder -d /opt/logstash-forwarder -s /sbin/nologin -c "logstash-forwarder" logstash-forwarder
error: %pre(logstash-forwarder-0.4.0-1.x86_64) scriptlet failed, exit status 139
error:   install: %pre scriptlet failed (2), skipping logstash-forwarder-0.4.0-1

Any idea what the problem might be?

**Comment by electrical** [comment]
Hi,

What distro are you using?
Seg faults could mean your system is having some serious issues btw

**Comment by blee1170** [comment]
Centos 6.6. These are VMs that are running in our internal cloud instance. I have not had any problems before with installing packages.

**Comment by electrical** [comment]
Hmm, I'm doing system tests on Centos 6.4 and 7.0 and never seen that error.
Since it uses the local useradd command and stuff it should work fine.
Can you try the command manually and see what happens?

**Comment by blee1170** [comment]
Running this command: useradd -r -g logstash-forwarder -d /opt/logstash-forwarder -s /sbin/nologin -c "logstash-forwarder" logstash-forwarder

It worked just fine (using sudo).

**Comment by blee1170** [comment]
So a rebuilt the VM and its working fine now. Super strange issue.

**Comment by electrical** [comment]
Computers are weird :-)
Closing the issue.

**Comment by bluebenno** [comment]
I got this too - AWS with Amazon linux and for some reason groupadd doesn't add the group to /etc/group and doesn't return an error.  Relaunched and it all worked.  Oddness.
